services:
  ms-discovery:
    image: ms-discovery:1.0.0
    restart: always
    mem_limit: 400m
    ports:
      - "8701:8701"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\DiscoveryServer\logs:/DiscoveryServer/logs
    networks:
      - mrk27-network
  ms-gateway:
    image: ms-gateway:1.0.0
    restart: always
    mem_limit: 400m
    ports:
      - "8282:8282"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\gateway\logs:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/gateway/logs
    environment:
      DISCOVERY_URL: ${DISCOVERY_URL}
    networks:
      - mrk27-network
    depends_on:
      - ms-discovery
  ms-inventory:
    image: ms-inventory:1.0.1
    restart: always
    mem_limit: 400m
    ports:
      - "1234:1236"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\inventory\logs:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/inventory/logs
    environment:
      DISCOVERY_URL: ${DISCOVERY_URL}
      PROFILE: ${prod}
      URL: ${POSTGRES_URL}
      USER_NAME: ${POSTGRES_USER}
      PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - mrk27-network
    depends_on:
      - ms-discovery
  ms-orders:
    image: ms-orders:1.0.0
    restart: always
    mem_limit: 400m
    ports:
      - "5678:5678"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\orders\logs:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/orders/logs
    environment:
      DISCOVERY_URL: ${DISCOVERY_URL}
    networks:
      - mrk27-network
    depends_on:
      - ms-discovery
  ms-reviews:
    image: ms-reviews:1.0.0
    restart: always
    mem_limit: 400m
    ports:
      - "9112:9112"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\reviews\logs:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/reviews/logs
    environment:
      DISCOVERY_URL: ${DISCOVERY_URL}
    networks:
      - mrk27-network
    depends_on:
      - ms-discovery

  postgres:
    image: postgres
    mem_limit: 512m
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      #POSTGRES_DB: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - /Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/postgres:/var/lib/postgresql/data
    networks:
      - mrk27-network

networks:
    mrk27-network:
      external: true
