services:
  ms-gateway:
    image: ms-gateway:1.0.0
    restart: always
    mem_limit: 400m
    ports:
      - "8282:8282"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\gateway\logs:/Users/Mirko Alarcon/Documents/UCB/I-2023/ArqSoftware/ProyectoMS/gateway/logs
    networks:
      - mrk27-network
    depends_on:
      - ms-discovery
  ms-discovery:
    image: ms-discovery:1.0.0
    restart: always
    mem_limit: 400m
    ports:
      - "8701:8701"
    volumes:
      - C:\Users\Mirko Alarcon\Documents\UCB\I-2023\ArqSoftware\ProyectoMS\DiscoveryServer\logs:/DiscoveryServer/logs
    networks:
      - mrk27-network

networks:
    mrk27-network:
      external: true
