server:
  port: 8282

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
              - allowedOrigins:
                - "localhost:4200"
              - allowedMethods:
                - "GET"
                - "POST"
                - "PUT"
                - "DELETE"
                - "OPTIONS"
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/ms-customer/**
          filters:
            - RewritePath=/ms-customer/(?<segment>.*), /$\{segment}
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/ms-account/**
          filters:
            - RewritePath=/ms-account/(?<segment>.*), /$\{segment}
# automatic discovery of services
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://ms-discovery:8701/eureka/
