server:
  port: 8282
spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      global-cors:
        cors-configurations:
          '[/**]':
            allowedHeaders:
              - "Authorization"
              - "Content-Type"
              - "Accept"
              - "Origin"
              - "Content-Length"
              - "X-Requested-With"
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS

      routes:
        - id: ms-inventory
          uri: lb://ms-inventory
          predicates:
            - Path=/ms-inventory/**
          filters:
            - RewritePath=/ms-inventory/(?<segment>.*), /$\{segment}
        - id: ms-orders
          uri: lb://ms-order
          predicates:
            - Path=/ms-order/**
          filters:
            - RewritePath=/ms-order/(?<segment>.*), /$\{segment}
        - id: ms-reviews
          uri: lb://ms-reviews
          predicates:
            - Path=/ms-reviews/**
          filters:
            - RewritePath=/ms-reviews/(?<segment>.*), /$\{segment}
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true


management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://localhost:8710/eureka/}


