server:
  port: 8282

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      globalcors:
        cors-configurations:
            '[/**]':
              - allowedOrigins:
                - "localhost:4200"
              - allowedMethods:
                - "GET"
                - "POST"
                - "PUT"
                - "DELETE"
                - "OPTIONS"
      routes:
        - id: ms-customer
          uri: lb://ms-customer
          predicates:
            - Path=/ms-customer/**
          filters:
            - RewritePath=/ms-customer/(?<segment>.*), /$\{segment}
        - id: ms-account
          uri: lb://ms-account
          predicates:
            - Path=/ms-account/**
          filters:
            - RewritePath=/ms-account/(?<segment>.*), /$\{segment}
# automatic discovery of services
#      discovery:
#        locator:
#          enabled: true
#          lower-case-service-id: true
#          predicates:
#            - Path=/ms-customer/**

#  datasource:
#    type: org.postgresql.jdbc2.optional.SimpleDataSource
#    username: ${USER_NAME:postgres}
#    password: ${PASSWORD:mysecretpassword}
#    url: ${URL:jdbc:postgresql://localhost:5432/postgres}
#  config:
#    import: optional:file:.env[.properties]
#  jpa:
#    hibernate:
#      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: gateway

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: ${DISCOVERY_URL:http://ms-discovery:8701/eureka/}
